#ifndef MINISHELL_MINISHELL_LIMIT_H
#define MINISHELL_MINISHELL_LIMIT_H

#define MS_MAX_ARG 40000

# define MS_SIZE_MAX_ENV 5
# define MS_SIZE_MAX_ENV_STR "100"

# define MS_SIZE_BUFFER 4095
# define MS_SIZE_BUFFER_FULL 4096
# define MS_SIZE_BUFFER_STR "4095"

# define MS_LENGTH_MAX_ENV_VAR 1023
# define MS_LENGTH_MAX_ENV_VAR_STR "1023"

# define MS_MAX_LENGTH_VAR MS_SIZE_BUFFER

#endif //MINISHELL_MINISHELL_LIMIT_H
